# ==============================================================================
# VPJD GEOGRAPHY MODULE
# geography_06c1_validate_taxon_geographic_distribution.R
#
# PURPOSE
# -------
# Independently validate the canonical taxon x geographic-unit distribution
# and evidence products generated by:
#
#   geography_06c_build_taxon_geographic_distribution.R
#
#
# PRINCIPLE
# ---------
#
# This is a POST-BUILD validation script.
#
# It deliberately:
#
#   - starts from a clean analytical state;
#   - reads the release products back from disk;
#   - independently reads VPJD Taxonomic Release v1.0.0;
#   - independently reads the frozen VPJD Geography vocabulary;
#   - does NOT use objects created by 06c;
#   - does NOT rebuild the distribution from the analytical source matrix;
#   - does NOT alter any release product.
#
#
# PRODUCTS VALIDATED
# ------------------
#
#   vpjd_taxon_geographic_distribution_v1.0.0.csv
#
#   vpjd_taxon_geographic_evidence_v1.0.0.csv
#
#
# EXPECTED RELEASE STRUCTURE
# --------------------------
#
#   published recognised taxa                         12,037
#   frozen geographic concepts                          418
#   Japanese botanical areas                             51
#   WCVP/TDWG reference concepts                        367
#
#   complete analytical combination universe         613,887
#   positive taxon x area relationships              128,824
#   unsupported analytical combinations              485,063
#
#   taxa with positive geographic evidence            11,470
#   taxa without positive geographic evidence            567
#   Japanese botanical areas represented                  51
#
#
# EVIDENCE SEMANTICS
# ------------------
#
# Positive evidence in VPJD Geography v1.0.0 is:
#
#   n_occurrence_records > 0
#
# with:
#
#   n_unique_occurrences > 0
#
# required to agree for every published evidence relationship.
#
#
# IMPORTANT
# ---------
#
# Missing taxon x geographic-unit relationships are NOT interpreted as
# absences.
#
# The distribution product represents positive evidence only.
#
#
# THIS SCRIPT VALIDATES
# ---------------------
#
#   1. file existence;
#   2. required schemas;
#   3. expected cardinalities;
#   4. taxonomic foreign-key integrity;
#   5. geographic foreign-key integrity;
#   6. uniqueness of taxon x geographic-unit relationships;
#   7. positive-evidence semantics;
#   8. exact relationship agreement between distribution and evidence;
#   9. exact taxon coverage agreement;
#  10. exact geographic coverage agreement;
#  11. taxon names against VPJD Taxonomic Release v1.0.0;
#  12. geographic names/codes against the frozen vocabulary;
#  13. per-taxon geographic coverage;
#  14. per-area taxonomic coverage;
#  15. the set of 567 recognised taxa lacking positive geographic evidence;
#  16. release labels and status fields;
#  17. final release-readiness gate.
#
#
# THIS SCRIPT DOES NOT
# --------------------
#
#   - modify release products;
#   - regenerate identifiers;
#   - fuzzy-match names;
#   - infer absence;
#   - infer distribution from WCVP/TDWG reference geography;
#   - apply Nakamura logic;
#   - assign Star categories;
#   - infer endemicity;
#   - infer rarity.
#
# ==============================================================================


# ------------------------------------------------------------------------------
# 01. RELEASE CONSTANTS
# ------------------------------------------------------------------------------

RELEASE_NAME <- "VPJD Geography v1.0.0"

SCRIPT_NAME <- "geography_06c1_validate_taxon_geographic_distribution.R"

BUILD_DATE <- format(
  Sys.Date(),
  "%Y-%m-%d"
)


EXPECTED_RECOGNISED_TAXA <- 12037L

EXPECTED_GEOGRAPHIC_CONCEPTS <- 418L

EXPECTED_JAPAN_BOTANICAL_AREAS <- 51L

EXPECTED_WCVP_TDWG_CONCEPTS <- 367L


EXPECTED_COMPLETE_COMBINATIONS <- 613887L

EXPECTED_POSITIVE_COMBINATIONS <- 128824L

EXPECTED_UNSUPPORTED_COMBINATIONS <- 485063L

EXPECTED_TAXA_WITH_EVIDENCE <- 11470L

EXPECTED_TAXA_WITHOUT_EVIDENCE <- 567L


EXPECTED_OCCURRENCE_STATUS <- "PRESENT_EVIDENCE"

EXPECTED_EVIDENCE_TYPE <- "POSITIVE_OCCURRENCE_EVIDENCE"

EXPECTED_EVIDENCE_RULE <- "n_occurrence_records > 0"

EXPECTED_CONCEPT_GROUP <- "JAPAN_BOTANICAL_AREA"

EXPECTED_IDENTIFIER_STATUS <- "FROZEN_VPJD_GEOGRAPHY_V1.0.0"


# ------------------------------------------------------------------------------
# 02. PROJECT PATHS
# ------------------------------------------------------------------------------

PROJECT_ROOT <- "I:/R/OJPCP/VPJD-OJPCP"

PUBLISHED_VPJD_ROOT <- "I:/R/Data/VPJD_v1.0.0"


DATA_ROOT <- file.path(
  PROJECT_ROOT,
  "data"
)


DERIVED_GEOGRAPHY_ROOT <- file.path(
  DATA_ROOT,
  "derived",
  "geography"
)


RELEASE_ROOT <- file.path(
  DERIVED_GEOGRAPHY_ROOT,
  "release_v1.0.0"
)


FROZEN_GEOGRAPHY_ROOT <- file.path(
  RELEASE_ROOT,
  "canonical_geographic_units_frozen"
)


DISTRIBUTION_ROOT <- file.path(
  RELEASE_ROOT,
  "taxon_geographic_distribution"
)


AUDIT_ROOT <- file.path(
  PROJECT_ROOT,
  "audit",
  "geography",
  "release_v1.0.0",
  "06c1_validate_taxon_geographic_distribution"
)


dir.create(
  AUDIT_ROOT,
  recursive = TRUE,
  showWarnings = FALSE
)


# ------------------------------------------------------------------------------
# 03. INPUT FILES
# ------------------------------------------------------------------------------

DISTRIBUTION_FILE <- file.path(
  DISTRIBUTION_ROOT,
  "vpjd_taxon_geographic_distribution_v1.0.0.csv"
)


EVIDENCE_FILE <- file.path(
  DISTRIBUTION_ROOT,
  "vpjd_taxon_geographic_evidence_v1.0.0.csv"
)


FROZEN_GEOGRAPHY_FILE <- file.path(
  FROZEN_GEOGRAPHY_ROOT,
  "vpjd_geographic_units_v1.0.0.csv"
)


# ------------------------------------------------------------------------------
# 04. OUTPUT FILES
# ------------------------------------------------------------------------------

FILE_AUDIT_FILE <- file.path(
  AUDIT_ROOT,
  "geography_06c1_file_audit.csv"
)


SCHEMA_AUDIT_FILE <- file.path(
  AUDIT_ROOT,
  "geography_06c1_schema_audit.csv"
)


DISTRIBUTION_SUMMARY_FILE <- file.path(
  AUDIT_ROOT,
  "geography_06c1_distribution_summary.csv"
)


TAXON_COVERAGE_FILE <- file.path(
  AUDIT_ROOT,
  "geography_06c1_taxon_coverage.csv"
)


AREA_COVERAGE_FILE <- file.path(
  AUDIT_ROOT,
  "geography_06c1_area_coverage.csv"
)


TAXA_WITHOUT_EVIDENCE_FILE <- file.path(
  AUDIT_ROOT,
  "geography_06c1_taxa_without_positive_evidence.csv"
)


RELATIONSHIP_COMPARISON_FILE <- file.path(
  AUDIT_ROOT,
  "geography_06c1_distribution_evidence_relationship_comparison.csv"
)


TAXON_REFERENCE_AUDIT_FILE <- file.path(
  AUDIT_ROOT,
  "geography_06c1_taxonomic_reference_audit.csv"
)


GEOGRAPHIC_REFERENCE_AUDIT_FILE <- file.path(
  AUDIT_ROOT,
  "geography_06c1_geographic_reference_audit.csv"
)


VALIDATION_GATE_FILE <- file.path(
  AUDIT_ROOT,
  "geography_06c1_validation_gate.csv"
)


RELEASE_GATE_FILE <- file.path(
  AUDIT_ROOT,
  "geography_06c1_release_gate.csv"
)


# ------------------------------------------------------------------------------
# 05. HELPER: NORMALISE TEXT
# ------------------------------------------------------------------------------

normalise_text <- function(x) {
  
  y <- as.character(x)
  
  y <- iconv(
    y,
    from = "",
    to = "UTF-8",
    sub = ""
  )
  
  y[is.na(y)] <- ""
  
  y <- trimws(y)
  
  
  empty_selector <- (
    y == "" |
      toupper(y) == "NA" |
      toupper(y) == "NULL"
  )
  
  
  empty_selector[is.na(empty_selector)] <- FALSE
  
  
  y[empty_selector] <- NA_character_
  
  
  y
}


# ------------------------------------------------------------------------------
# 06. HELPER: NORMALISE MATCH KEY
# ------------------------------------------------------------------------------

normalise_key <- function(x) {
  
  y <- normalise_text(x)
  
  y <- tolower(y)
  
  y <- gsub(
    "[[:space:]]+",
    " ",
    y
  )
  
  y <- trimws(y)
  
  y
}


# ------------------------------------------------------------------------------
# 07. HELPER: SAFE CSV READ
# ------------------------------------------------------------------------------

safe_read_csv <- function(path) {
  
  if (!file.exists(path)) {
    
    stop(
      paste0(
        "Required file not found:\n",
        path
      )
    )
  }
  
  
  attempts <- list(
    
    function() {
      
      read.csv(
        path,
        stringsAsFactors = FALSE,
        check.names = FALSE,
        fileEncoding = "UTF-8"
      )
    },
    
    function() {
      
      read.csv(
        path,
        stringsAsFactors = FALSE,
        check.names = FALSE,
        fileEncoding = "UTF-8-BOM"
      )
    },
    
    function() {
      
      read.csv(
        path,
        stringsAsFactors = FALSE,
        check.names = FALSE,
        fileEncoding = "latin1"
      )
    }
  )
  
  
  errors <- character(0)
  
  
  for (attempt_index in seq_along(attempts)) {
    
    result <- tryCatch(
      
      attempts[[attempt_index]](),
      
      error = function(e) {
        
        errors <<- c(
          errors,
          conditionMessage(e)
        )
        
        NULL
      }
    )
    
    
    if (!is.null(result)) {
      
      return(result)
    }
  }
  
  
  stop(
    paste0(
      "Unable to read CSV:\n",
      path,
      "\n\nErrors:\n",
      paste(
        errors,
        collapse = "\n"
      )
    )
  )
}


# ------------------------------------------------------------------------------
# 08. HELPER: FIND PUBLISHED RECOGNISED-TAXON TABLE
# ------------------------------------------------------------------------------

find_recognised_taxon_file <- function(root) {
  
  if (!dir.exists(root)) {
    
    stop(
      paste0(
        "Published VPJD root not found:\n",
        root
      )
    )
  }
  
  
  candidate_files <- list.files(
    root,
    pattern = "\\.csv$",
    recursive = TRUE,
    full.names = TRUE,
    ignore.case = TRUE
  )
  
  
  exact_selector <- (
    tolower(
      basename(candidate_files)
    ) ==
      "vpjd_recognised_taxa.csv"
  )
  
  
  exact_matches <- candidate_files[
    exact_selector
  ]
  
  
  if (length(exact_matches) == 0L) {
    
    stop(
      paste0(
        "Canonical recognised-taxon table not found under:\n",
        root,
        "\n\nExpected filename:\n",
        "vpjd_recognised_taxa.csv"
      )
    )
  }
  
  
  if (length(exact_matches) > 1L) {
    
    file_sizes <- file.info(
      exact_matches
    )$size
    
    
    exact_matches <- exact_matches[
      order(
        file_sizes,
        decreasing = TRUE
      )
    ]
  }
  
  
  exact_matches[1L]
}


# ------------------------------------------------------------------------------
# 09. HELPER: SHA-256
#
# Uses digest if available.
#
# Validation does NOT fail merely because digest is unavailable.
# ------------------------------------------------------------------------------

calculate_sha256 <- function(path) {
  
  if (!requireNamespace(
    "digest",
    quietly = TRUE
  )) {
    
    return(NA_character_)
  }
  
  
  digest::digest(
    file = path,
    algo = "sha256",
    serialize = FALSE
  )
}


# ------------------------------------------------------------------------------
# 10. START
# ------------------------------------------------------------------------------

cat("\n")
cat("============================================================\n")
cat(" VPJD GEOGRAPHY 06c1 - INDEPENDENT DISTRIBUTION VALIDATION\n")
cat("============================================================\n\n")


cat(
  "Release: ",
  RELEASE_NAME,
  "\n",
  sep = ""
)


cat(
  "Validation date: ",
  BUILD_DATE,
  "\n\n",
  sep = ""
)


# ------------------------------------------------------------------------------
# 11. LOCATE PUBLISHED TAXONOMIC INTERFACE
# ------------------------------------------------------------------------------

cat("Locating VPJD Taxonomic Release v1.0.0...\n")


RECOGNISED_TAXA_FILE <- find_recognised_taxon_file(
  PUBLISHED_VPJD_ROOT
)


cat(
  "Recognised-taxon table:\n",
  RECOGNISED_TAXA_FILE,
  "\n\n",
  sep = ""
)


# ------------------------------------------------------------------------------
# 12. FILE-LEVEL AUDIT
# ------------------------------------------------------------------------------

cat("Auditing required files...\n")


required_files <- c(
  RECOGNISED_TAXA_FILE,
  FROZEN_GEOGRAPHY_FILE,
  DISTRIBUTION_FILE,
  EVIDENCE_FILE
)


file_labels <- c(
  "published_recognised_taxa",
  "frozen_geographic_vocabulary",
  "canonical_distribution",
  "canonical_evidence"
)


file_exists_values <- file.exists(
  required_files
)


file_sizes <- rep(
  NA_real_,
  length(required_files)
)


file_modified <- rep(
  NA_character_,
  length(required_files)
)


file_sha256 <- rep(
  NA_character_,
  length(required_files)
)


for (file_index in seq_along(required_files)) {
  
  if (file_exists_values[file_index]) {
    
    file_information <- file.info(
      required_files[file_index]
    )
    
    
    file_sizes[file_index] <- file_information$size
    
    
    file_modified[file_index] <- format(
      file_information$mtime,
      "%Y-%m-%d %H:%M:%S"
    )
    
    
    file_sha256[file_index] <- calculate_sha256(
      required_files[file_index]
    )
  }
}


file_audit <- data.frame(
  
  file_role = file_labels,
  
  file_path = required_files,
  
  exists = file_exists_values,
  
  size_bytes = file_sizes,
  
  modified_time = file_modified,
  
  sha256 = file_sha256,
  
  stringsAsFactors = FALSE
)


write.csv(
  file_audit,
  FILE_AUDIT_FILE,
  row.names = FALSE,
  na = "",
  fileEncoding = "UTF-8"
)


if (!all(file_exists_values)) {
  
  stop(
    paste0(
      "One or more required release/reference files are missing.\n\n",
      "Review:\n",
      FILE_AUDIT_FILE
    )
  )
}


cat("Required files: PASS\n\n")


# ------------------------------------------------------------------------------
# 13. READ ALL PRODUCTS INDEPENDENTLY
# ------------------------------------------------------------------------------

cat("Reading release/reference products from disk...\n")


taxa <- safe_read_csv(
  RECOGNISED_TAXA_FILE
)


geography <- safe_read_csv(
  FROZEN_GEOGRAPHY_FILE
)


distribution <- safe_read_csv(
  DISTRIBUTION_FILE
)


evidence <- safe_read_csv(
  EVIDENCE_FILE
)


cat("Read complete.\n\n")


# ------------------------------------------------------------------------------
# 14. SCHEMA DEFINITIONS
# ------------------------------------------------------------------------------

required_taxon_fields <- c(
  "wcvp_plant_name_id",
  "wcvp_taxon_name"
)


required_geography_fields <- c(
  "geographic_unit_id",
  "geographic_code",
  "geographic_name",
  "concept_group",
  "identifier_status"
)


required_distribution_fields <- c(
  "wcvp_plant_name_id",
  "wcvp_taxon_name",
  "geographic_unit_id",
  "geographic_code",
  "geographic_name",
  "concept_group",
  "occurrence_status",
  "geography_release"
)


required_evidence_fields <- c(
  "wcvp_plant_name_id",
  "wcvp_taxon_name",
  "geographic_unit_id",
  "geographic_code",
  "geographic_name",
  "concept_group",
  "n_occurrence_records",
  "n_unique_occurrences",
  "occurrence_status",
  "evidence_type",
  "evidence_rule",
  "evidence_source_file",
  "evidence_source_row",
  "geography_release",
  "build_script",
  "build_date"
)


# ------------------------------------------------------------------------------
# 15. SCHEMA AUDIT
# ------------------------------------------------------------------------------

schema_audit <- data.frame(
  
  product = c(
    "published_taxonomy",
    "frozen_geography",
    "distribution",
    "evidence"
  ),
  
  n_rows = c(
    nrow(taxa),
    nrow(geography),
    nrow(distribution),
    nrow(evidence)
  ),
  
  n_columns = c(
    ncol(taxa),
    ncol(geography),
    ncol(distribution),
    ncol(evidence)
  ),
  
  required_fields = c(
    paste(
      required_taxon_fields,
      collapse = ";"
    ),
    paste(
      required_geography_fields,
      collapse = ";"
    ),
    paste(
      required_distribution_fields,
      collapse = ";"
    ),
    paste(
      required_evidence_fields,
      collapse = ";"
    )
  ),
  
  missing_fields = c(
    paste(
      setdiff(
        required_taxon_fields,
        names(taxa)
      ),
      collapse = ";"
    ),
    paste(
      setdiff(
        required_geography_fields,
        names(geography)
      ),
      collapse = ";"
    ),
    paste(
      setdiff(
        required_distribution_fields,
        names(distribution)
      ),
      collapse = ";"
    ),
    paste(
      setdiff(
        required_evidence_fields,
        names(evidence)
      ),
      collapse = ";"
    )
  ),
  
  stringsAsFactors = FALSE
)


schema_audit$schema_pass <- (
  schema_audit$missing_fields == ""
)


write.csv(
  schema_audit,
  SCHEMA_AUDIT_FILE,
  row.names = FALSE,
  na = "",
  fileEncoding = "UTF-8"
)


if (!all(schema_audit$schema_pass)) {
  
  stop(
    paste0(
      "One or more product schemas failed validation.\n\n",
      "Review:\n",
      SCHEMA_AUDIT_FILE
    )
  )
}


cat("Schemas: PASS\n\n")


# ------------------------------------------------------------------------------
# 16. NORMALISE TAXONOMIC REFERENCE
# ------------------------------------------------------------------------------

taxon_id <- normalise_text(
  taxa$wcvp_plant_name_id
)


taxon_name <- normalise_text(
  taxa$wcvp_taxon_name
)


if (nrow(taxa) != EXPECTED_RECOGNISED_TAXA) {
  
  stop(
    paste0(
      "Published taxonomy contains ",
      nrow(taxa),
      " rows; expected ",
      EXPECTED_RECOGNISED_TAXA,
      "."
    )
  )
}


if (
  any(is.na(taxon_id)) ||
  any(duplicated(taxon_id))
) {
  
  stop(
    "Published taxonomy has incomplete or duplicate canonical taxon IDs."
  )
}


# ------------------------------------------------------------------------------
# 17. NORMALISE GEOGRAPHIC REFERENCE
# ------------------------------------------------------------------------------

geo_id <- normalise_text(
  geography$geographic_unit_id
)


geo_code <- normalise_text(
  geography$geographic_code
)


geo_name <- normalise_text(
  geography$geographic_name
)


geo_group <- normalise_text(
  geography$concept_group
)


geo_identifier_status <- normalise_text(
  geography$identifier_status
)


japan_geo_selector <- (
  geo_group ==
    EXPECTED_CONCEPT_GROUP
)


japan_geo_selector[
  is.na(japan_geo_selector)
] <- FALSE


wcvp_geo_selector <- (
  geo_group ==
    "WCVP_TDWG_LOCATION"
)


wcvp_geo_selector[
  is.na(wcvp_geo_selector)
] <- FALSE


japan_geography <- geography[
  japan_geo_selector,
  ,
  drop = FALSE
]


japan_geo_id <- normalise_text(
  japan_geography$geographic_unit_id
)


japan_geo_code <- normalise_text(
  japan_geography$geographic_code
)


japan_geo_name <- normalise_text(
  japan_geography$geographic_name
)


if (nrow(geography) != EXPECTED_GEOGRAPHIC_CONCEPTS) {
  
  stop(
    paste0(
      "Frozen geography contains ",
      nrow(geography),
      " rows; expected ",
      EXPECTED_GEOGRAPHIC_CONCEPTS,
      "."
    )
  )
}


if (
  any(is.na(geo_id)) ||
  any(duplicated(geo_id))
) {
  
  stop(
    "Frozen geographic vocabulary has incomplete or duplicate IDs."
  )
}


# ------------------------------------------------------------------------------
# 18. NORMALISE DISTRIBUTION PRODUCT
# ------------------------------------------------------------------------------

distribution_taxon_id <- normalise_text(
  distribution$wcvp_plant_name_id
)


distribution_taxon_name <- normalise_text(
  distribution$wcvp_taxon_name
)


distribution_geo_id <- normalise_text(
  distribution$geographic_unit_id
)


distribution_geo_code <- normalise_text(
  distribution$geographic_code
)


distribution_geo_name <- normalise_text(
  distribution$geographic_name
)


distribution_group <- normalise_text(
  distribution$concept_group
)


distribution_status <- normalise_text(
  distribution$occurrence_status
)


distribution_release <- normalise_text(
  distribution$geography_release
)


distribution_relationship_key <- paste(
  distribution_taxon_id,
  distribution_geo_id,
  sep = "||"
)


# ------------------------------------------------------------------------------
# 19. NORMALISE EVIDENCE PRODUCT
# ------------------------------------------------------------------------------

evidence_taxon_id <- normalise_text(
  evidence$wcvp_plant_name_id
)


evidence_taxon_name <- normalise_text(
  evidence$wcvp_taxon_name
)


evidence_geo_id <- normalise_text(
  evidence$geographic_unit_id
)


evidence_geo_code <- normalise_text(
  evidence$geographic_code
)


evidence_geo_name <- normalise_text(
  evidence$geographic_name
)


evidence_group <- normalise_text(
  evidence$concept_group
)


evidence_status <- normalise_text(
  evidence$occurrence_status
)


evidence_type <- normalise_text(
  evidence$evidence_type
)


evidence_rule <- normalise_text(
  evidence$evidence_rule
)


evidence_release <- normalise_text(
  evidence$geography_release
)


evidence_occurrence_count <- suppressWarnings(
  as.numeric(
    evidence$n_occurrence_records
  )
)


evidence_unique_count <- suppressWarnings(
  as.numeric(
    evidence$n_unique_occurrences
  )
)


evidence_relationship_key <- paste(
  evidence_taxon_id,
  evidence_geo_id,
  sep = "||"
)


# ------------------------------------------------------------------------------
# 20. BASIC DISTRIBUTION CARDINALITY
# ------------------------------------------------------------------------------

n_distribution_rows <- nrow(
  distribution
)


n_distribution_taxa <- length(
  unique(
    distribution_taxon_id
  )
)


n_distribution_areas <- length(
  unique(
    distribution_geo_id
  )
)


n_distribution_duplicate_keys <- sum(
  duplicated(
    distribution_relationship_key
  )
)


n_distribution_taxa_without_evidence <- (
  EXPECTED_RECOGNISED_TAXA -
    n_distribution_taxa
)


# ------------------------------------------------------------------------------
# 21. BASIC EVIDENCE CARDINALITY
# ------------------------------------------------------------------------------

n_evidence_rows <- nrow(
  evidence
)


n_evidence_taxa <- length(
  unique(
    evidence_taxon_id
  )
)


n_evidence_areas <- length(
  unique(
    evidence_geo_id
  )
)


n_evidence_duplicate_keys <- sum(
  duplicated(
    evidence_relationship_key
  )
)


# ------------------------------------------------------------------------------
# 22. TAXONOMIC REFERENTIAL INTEGRITY
# ------------------------------------------------------------------------------

distribution_taxon_match <- match(
  distribution_taxon_id,
  taxon_id
)


evidence_taxon_match <- match(
  evidence_taxon_id,
  taxon_id
)


distribution_taxon_reference_failure <- is.na(
  distribution_taxon_match
)


evidence_taxon_reference_failure <- is.na(
  evidence_taxon_match
)


distribution_taxon_name_match <- rep(
  FALSE,
  nrow(distribution)
)


distribution_taxon_name_match[
  !distribution_taxon_reference_failure
] <- (
  normalise_key(
    distribution_taxon_name[
      !distribution_taxon_reference_failure
    ]
  ) ==
    normalise_key(
      taxon_name[
        distribution_taxon_match[
          !distribution_taxon_reference_failure
        ]
      ]
    )
)


evidence_taxon_name_match <- rep(
  FALSE,
  nrow(evidence)
)


evidence_taxon_name_match[
  !evidence_taxon_reference_failure
] <- (
  normalise_key(
    evidence_taxon_name[
      !evidence_taxon_reference_failure
    ]
  ) ==
    normalise_key(
      taxon_name[
        evidence_taxon_match[
          !evidence_taxon_reference_failure
        ]
      ]
    )
)


taxon_reference_audit <- data.frame(
  
  product = c(
    rep(
      "distribution",
      nrow(distribution)
    ),
    rep(
      "evidence",
      nrow(evidence)
    )
  ),
  
  wcvp_plant_name_id = c(
    distribution_taxon_id,
    evidence_taxon_id
  ),
  
  product_taxon_name = c(
    distribution_taxon_name,
    evidence_taxon_name
  ),
  
  taxon_reference_found = c(
    !distribution_taxon_reference_failure,
    !evidence_taxon_reference_failure
  ),
  
  taxon_name_match = c(
    distribution_taxon_name_match,
    evidence_taxon_name_match
  ),
  
  stringsAsFactors = FALSE
)


write.csv(
  taxon_reference_audit,
  TAXON_REFERENCE_AUDIT_FILE,
  row.names = FALSE,
  na = "",
  fileEncoding = "UTF-8"
)


# ------------------------------------------------------------------------------
# 23. GEOGRAPHIC REFERENTIAL INTEGRITY
# ------------------------------------------------------------------------------

distribution_geo_match <- match(
  distribution_geo_id,
  japan_geo_id
)


evidence_geo_match <- match(
  evidence_geo_id,
  japan_geo_id
)


distribution_geo_reference_failure <- is.na(
  distribution_geo_match
)


evidence_geo_reference_failure <- is.na(
  evidence_geo_match
)


distribution_geo_code_match <- rep(
  FALSE,
  nrow(distribution)
)


distribution_geo_name_match <- rep(
  FALSE,
  nrow(distribution)
)


valid_distribution_geo <- (
  !distribution_geo_reference_failure
)


distribution_geo_code_match[
  valid_distribution_geo
] <- (
  normalise_key(
    distribution_geo_code[
      valid_distribution_geo
    ]
  ) ==
    normalise_key(
      japan_geo_code[
        distribution_geo_match[
          valid_distribution_geo
        ]
      ]
    )
)


distribution_geo_name_match[
  valid_distribution_geo
] <- (
  normalise_key(
    distribution_geo_name[
      valid_distribution_geo
    ]
  ) ==
    normalise_key(
      japan_geo_name[
        distribution_geo_match[
          valid_distribution_geo
        ]
      ]
    )
)


evidence_geo_code_match <- rep(
  FALSE,
  nrow(evidence)
)


evidence_geo_name_match <- rep(
  FALSE,
  nrow(evidence)
)


valid_evidence_geo <- (
  !evidence_geo_reference_failure
)


evidence_geo_code_match[
  valid_evidence_geo
] <- (
  normalise_key(
    evidence_geo_code[
      valid_evidence_geo
    ]
  ) ==
    normalise_key(
      japan_geo_code[
        evidence_geo_match[
          valid_evidence_geo
        ]
      ]
    )
)


evidence_geo_name_match[
  valid_evidence_geo
] <- (
  normalise_key(
    evidence_geo_name[
      valid_evidence_geo
    ]
  ) ==
    normalise_key(
      japan_geo_name[
        evidence_geo_match[
          valid_evidence_geo
        ]
      ]
    )
)


geographic_reference_audit <- data.frame(
  
  product = c(
    rep(
      "distribution",
      nrow(distribution)
    ),
    rep(
      "evidence",
      nrow(evidence)
    )
  ),
  
  geographic_unit_id = c(
    distribution_geo_id,
    evidence_geo_id
  ),
  
  product_geographic_code = c(
    distribution_geo_code,
    evidence_geo_code
  ),
  
  product_geographic_name = c(
    distribution_geo_name,
    evidence_geo_name
  ),
  
  geographic_reference_found = c(
    !distribution_geo_reference_failure,
    !evidence_geo_reference_failure
  ),
  
  geographic_code_match = c(
    distribution_geo_code_match,
    evidence_geo_code_match
  ),
  
  geographic_name_match = c(
    distribution_geo_name_match,
    evidence_geo_name_match
  ),
  
  stringsAsFactors = FALSE
)


write.csv(
  geographic_reference_audit,
  GEOGRAPHIC_REFERENCE_AUDIT_FILE,
  row.names = FALSE,
  na = "",
  fileEncoding = "UTF-8"
)


# ------------------------------------------------------------------------------
# 24. COMPARE DISTRIBUTION AND EVIDENCE RELATIONSHIP SETS
# ------------------------------------------------------------------------------

cat("Comparing distribution and evidence relationship sets...\n")


distribution_only_keys <- setdiff(
  unique(
    distribution_relationship_key
  ),
  unique(
    evidence_relationship_key
  )
)


evidence_only_keys <- setdiff(
  unique(
    evidence_relationship_key
  ),
  unique(
    distribution_relationship_key
  )
)


all_relationship_keys <- union(
  unique(
    distribution_relationship_key
  ),
  unique(
    evidence_relationship_key
  )
)


relationship_comparison <- data.frame(
  
  relationship_key =
    all_relationship_keys,
  
  in_distribution =
    all_relationship_keys %in%
    distribution_relationship_key,
  
  in_evidence =
    all_relationship_keys %in%
    evidence_relationship_key,
  
  stringsAsFactors = FALSE
)


relationship_comparison$agreement <- (
  relationship_comparison$in_distribution ==
    relationship_comparison$in_evidence
)


write.csv(
  relationship_comparison,
  RELATIONSHIP_COMPARISON_FILE,
  row.names = FALSE,
  na = "",
  fileEncoding = "UTF-8"
)


n_distribution_only_relationships <- length(
  distribution_only_keys
)


n_evidence_only_relationships <- length(
  evidence_only_keys
)


n_relationship_disagreements <- sum(
  !relationship_comparison$agreement
)


# ------------------------------------------------------------------------------
# 25. VALIDATE POSITIVE EVIDENCE SEMANTICS
# ------------------------------------------------------------------------------

evidence_occurrence_positive <- (
  evidence_occurrence_count > 0
)


evidence_unique_positive <- (
  evidence_unique_count > 0
)


evidence_occurrence_positive[
  is.na(evidence_occurrence_positive)
] <- FALSE


evidence_unique_positive[
  is.na(evidence_unique_positive)
] <- FALSE


evidence_selector_disagreement <- (
  evidence_occurrence_positive !=
    evidence_unique_positive
)


evidence_selector_disagreement[
  is.na(evidence_selector_disagreement)
] <- TRUE


n_nonpositive_occurrence_rows <- sum(
  !evidence_occurrence_positive
)


n_nonpositive_unique_rows <- sum(
  !evidence_unique_positive
)


n_evidence_selector_disagreements <- sum(
  evidence_selector_disagreement
)


# ------------------------------------------------------------------------------
# 26. TAXON COVERAGE PROFILE
# ------------------------------------------------------------------------------

cat("Building independent per-taxon coverage profile...\n")


taxon_coverage_counts <- table(
  distribution_taxon_id
)


taxon_coverage <- data.frame(
  
  wcvp_plant_name_id =
    taxon_id,
  
  wcvp_taxon_name =
    taxon_name,
  
  n_geographic_units =
    as.integer(
      taxon_coverage_counts[
        taxon_id
      ]
    ),
  
  stringsAsFactors = FALSE
)


taxon_coverage$n_geographic_units[
  is.na(
    taxon_coverage$n_geographic_units
  )
] <- 0L


taxon_coverage$has_positive_geographic_evidence <- (
  taxon_coverage$n_geographic_units > 0L
)


taxon_coverage <- taxon_coverage[
  order(
    -taxon_coverage$n_geographic_units,
    taxon_coverage$wcvp_taxon_name
  ),
  ,
  drop = FALSE
]


rownames(
  taxon_coverage
) <- NULL


write.csv(
  taxon_coverage,
  TAXON_COVERAGE_FILE,
  row.names = FALSE,
  na = "",
  fileEncoding = "UTF-8"
)


# ------------------------------------------------------------------------------
# 27. TAXA WITHOUT POSITIVE EVIDENCE
# ------------------------------------------------------------------------------

taxa_without_evidence <- taxon_coverage[
  !taxon_coverage$has_positive_geographic_evidence,
  ,
  drop = FALSE
]


taxa_without_evidence <- taxa_without_evidence[
  order(
    taxa_without_evidence$wcvp_taxon_name
  ),
  ,
  drop = FALSE
]


rownames(
  taxa_without_evidence
) <- NULL


write.csv(
  taxa_without_evidence,
  TAXA_WITHOUT_EVIDENCE_FILE,
  row.names = FALSE,
  na = "",
  fileEncoding = "UTF-8"
)


n_taxa_without_evidence_independent <- nrow(
  taxa_without_evidence
)


# ------------------------------------------------------------------------------
# 28. AREA COVERAGE PROFILE
# ------------------------------------------------------------------------------

cat("Building independent per-area coverage profile...\n")


area_relationship_counts <- table(
  distribution_geo_id
)


area_taxon_counts <- tapply(
  distribution_taxon_id,
  distribution_geo_id,
  function(x) {
    length(
      unique(x)
    )
  }
)


area_evidence_rows <- table(
  evidence_geo_id
)


area_occurrence_records <- tapply(
  evidence_occurrence_count,
  evidence_geo_id,
  sum,
  na.rm = TRUE
)


area_unique_occurrences <- tapply(
  evidence_unique_count,
  evidence_geo_id,
  sum,
  na.rm = TRUE
)


area_coverage <- data.frame(
  
  geographic_unit_id =
    japan_geo_id,
  
  geographic_code =
    japan_geo_code,
  
  geographic_name =
    japan_geo_name,
  
  n_distribution_relationships =
    as.integer(
      area_relationship_counts[
        japan_geo_id
      ]
    ),
  
  n_distinct_taxa =
    as.integer(
      area_taxon_counts[
        japan_geo_id
      ]
    ),
  
  n_evidence_rows =
    as.integer(
      area_evidence_rows[
        japan_geo_id
      ]
    ),
  
  total_occurrence_records =
    as.numeric(
      area_occurrence_records[
        japan_geo_id
      ]
    ),
  
  total_unique_occurrences =
    as.numeric(
      area_unique_occurrences[
        japan_geo_id
      ]
    ),
  
  stringsAsFactors = FALSE
)


numeric_area_fields <- c(
  "n_distribution_relationships",
  "n_distinct_taxa",
  "n_evidence_rows",
  "total_occurrence_records",
  "total_unique_occurrences"
)


for (field_name in numeric_area_fields) {
  
  missing_selector <- is.na(
    area_coverage[[field_name]]
  )
  
  
  area_coverage[[field_name]][
    missing_selector
  ] <- 0
}


area_coverage <- area_coverage[
  order(
    -area_coverage$n_distinct_taxa,
    area_coverage$geographic_name
  ),
  ,
  drop = FALSE
]


rownames(
  area_coverage
) <- NULL


write.csv(
  area_coverage,
  AREA_COVERAGE_FILE,
  row.names = FALSE,
  na = "",
  fileEncoding = "UTF-8"
)


# ------------------------------------------------------------------------------
# 29. CROSS-PRODUCT ARITHMETIC
# ------------------------------------------------------------------------------

independent_complete_combination_count <- (
  nrow(taxa) *
    nrow(japan_geography)
)


independent_unsupported_combination_count <- (
  independent_complete_combination_count -
    n_distribution_rows
)


# ------------------------------------------------------------------------------
# 30. PRODUCT STATUS / RELEASE LABEL TESTS
# ------------------------------------------------------------------------------

distribution_status_pass <- (
  !any(is.na(distribution_status)) &&
    all(
      distribution_status ==
        EXPECTED_OCCURRENCE_STATUS
    )
)


distribution_group_pass <- (
  !any(is.na(distribution_group)) &&
    all(
      distribution_group ==
        EXPECTED_CONCEPT_GROUP
    )
)


distribution_release_pass <- (
  !any(is.na(distribution_release)) &&
    all(
      distribution_release ==
        RELEASE_NAME
    )
)


evidence_status_pass <- (
  !any(is.na(evidence_status)) &&
    all(
      evidence_status ==
        EXPECTED_OCCURRENCE_STATUS
    )
)


evidence_type_pass <- (
  !any(is.na(evidence_type)) &&
    all(
      evidence_type ==
        EXPECTED_EVIDENCE_TYPE
    )
)


evidence_rule_pass <- (
  !any(is.na(evidence_rule)) &&
    all(
      evidence_rule ==
        EXPECTED_EVIDENCE_RULE
    )
)


evidence_group_pass <- (
  !any(is.na(evidence_group)) &&
    all(
      evidence_group ==
        EXPECTED_CONCEPT_GROUP
    )
)


evidence_release_pass <- (
  !any(is.na(evidence_release)) &&
    all(
      evidence_release ==
        RELEASE_NAME
    )
)


# ------------------------------------------------------------------------------
# 31. DISTRIBUTION SUMMARY
# ------------------------------------------------------------------------------

distribution_summary <- data.frame(
  
  metric = c(
    "published_recognised_taxa",
    "frozen_geographic_concepts",
    "frozen_japanese_botanical_areas",
    "frozen_wcvp_tdwg_reference_concepts",
    "independent_complete_combination_universe",
    "distribution_rows",
    "evidence_rows",
    "distribution_distinct_taxa",
    "evidence_distinct_taxa",
    "taxa_without_positive_evidence",
    "distribution_distinct_geographic_units",
    "evidence_distinct_geographic_units",
    "independent_unsupported_combinations",
    "distribution_duplicate_relationship_keys",
    "evidence_duplicate_relationship_keys",
    "distribution_only_relationships",
    "evidence_only_relationships",
    "relationship_set_disagreements",
    "distribution_taxon_reference_failures",
    "evidence_taxon_reference_failures",
    "distribution_taxon_name_mismatches",
    "evidence_taxon_name_mismatches",
    "distribution_geographic_reference_failures",
    "evidence_geographic_reference_failures",
    "distribution_geographic_code_mismatches",
    "evidence_geographic_code_mismatches",
    "distribution_geographic_name_mismatches",
    "evidence_geographic_name_mismatches",
    "evidence_nonpositive_occurrence_rows",
    "evidence_nonpositive_unique_occurrence_rows",
    "evidence_occurrence_unique_selector_disagreements"
  ),
  
  value = c(
    nrow(taxa),
    nrow(geography),
    nrow(japan_geography),
    sum(wcvp_geo_selector),
    independent_complete_combination_count,
    n_distribution_rows,
    n_evidence_rows,
    n_distribution_taxa,
    n_evidence_taxa,
    n_taxa_without_evidence_independent,
    n_distribution_areas,
    n_evidence_areas,
    independent_unsupported_combination_count,
    n_distribution_duplicate_keys,
    n_evidence_duplicate_keys,
    n_distribution_only_relationships,
    n_evidence_only_relationships,
    n_relationship_disagreements,
    sum(
      distribution_taxon_reference_failure
    ),
    sum(
      evidence_taxon_reference_failure
    ),
    sum(
      !distribution_taxon_reference_failure &
        !distribution_taxon_name_match
    ),
    sum(
      !evidence_taxon_reference_failure &
        !evidence_taxon_name_match
    ),
    sum(
      distribution_geo_reference_failure
    ),
    sum(
      evidence_geo_reference_failure
    ),
    sum(
      !distribution_geo_reference_failure &
        !distribution_geo_code_match
    ),
    sum(
      !evidence_geo_reference_failure &
        !evidence_geo_code_match
    ),
    sum(
      !distribution_geo_reference_failure &
        !distribution_geo_name_match
    ),
    sum(
      !evidence_geo_reference_failure &
        !evidence_geo_name_match
    ),
    n_nonpositive_occurrence_rows,
    n_nonpositive_unique_rows,
    n_evidence_selector_disagreements
  ),
  
  stringsAsFactors = FALSE
)


write.csv(
  distribution_summary,
  DISTRIBUTION_SUMMARY_FILE,
  row.names = FALSE,
  na = "",
  fileEncoding = "UTF-8"
)


# ------------------------------------------------------------------------------
# 32. VALIDATION GATE
# ------------------------------------------------------------------------------

validation_gate <- data.frame(
  
  criterion = c(
    
    "required_files_exist",
    
    "required_schemas_complete",
    
    "published_taxon_cardinality_12037",
    
    "published_taxon_ids_complete",
    
    "published_taxon_ids_unique",
    
    "frozen_geographic_cardinality_418",
    
    "frozen_japanese_botanical_areas_51",
    
    "frozen_wcvp_tdwg_concepts_367",
    
    "frozen_geographic_ids_complete",
    
    "frozen_geographic_ids_unique",
    
    "frozen_identifier_status_correct",
    
    "independent_complete_combination_universe_613887",
    
    "distribution_rows_128824",
    
    "evidence_rows_128824",
    
    "distribution_taxa_11470",
    
    "evidence_taxa_11470",
    
    "taxa_without_positive_evidence_567",
    
    "distribution_geographic_units_51",
    
    "evidence_geographic_units_51",
    
    "independent_unsupported_combinations_485063",
    
    "distribution_relationship_keys_unique",
    
    "evidence_relationship_keys_unique",
    
    "distribution_and_evidence_relationship_sets_identical",
    
    "distribution_taxonomic_foreign_keys_complete",
    
    "evidence_taxonomic_foreign_keys_complete",
    
    "distribution_taxon_names_match_taxonomic_release",
    
    "evidence_taxon_names_match_taxonomic_release",
    
    "distribution_geographic_foreign_keys_complete",
    
    "evidence_geographic_foreign_keys_complete",
    
    "distribution_geographic_codes_match_frozen_vocabulary",
    
    "evidence_geographic_codes_match_frozen_vocabulary",
    
    "distribution_geographic_names_match_frozen_vocabulary",
    
    "evidence_geographic_names_match_frozen_vocabulary",
    
    "all_evidence_occurrence_counts_positive",
    
    "all_evidence_unique_occurrence_counts_positive",
    
    "occurrence_and_unique_evidence_selectors_agree",
    
    "distribution_status_is_present_evidence",
    
    "evidence_status_is_present_evidence",
    
    "distribution_concept_group_is_japan_botanical_area",
    
    "evidence_concept_group_is_japan_botanical_area",
    
    "evidence_type_is_positive_occurrence_evidence",
    
    "evidence_rule_is_n_occurrence_records_gt_zero",
    
    "distribution_release_label_correct",
    
    "evidence_release_label_correct",
    
    "unsupported_combinations_are_not_distribution_rows",
    
    "distribution_is_not_complete_cross_product",
    
    "missing_relationships_not_encoded_as_absence",
    
    "wcvp_reference_geography_not_used_as_distribution",
    
    "nakamura_logic_not_required",
    
    "star_categories_not_required"
  ),
  
  passed = c(
    
    all(file_exists_values),
    
    all(schema_audit$schema_pass),
    
    nrow(taxa) ==
      EXPECTED_RECOGNISED_TAXA,
    
    !any(
      is.na(
        taxon_id
      )
    ),
    
    !any(
      duplicated(
        taxon_id
      )
    ),
    
    nrow(geography) ==
      EXPECTED_GEOGRAPHIC_CONCEPTS,
    
    nrow(japan_geography) ==
      EXPECTED_JAPAN_BOTANICAL_AREAS,
    
    sum(wcvp_geo_selector) ==
      EXPECTED_WCVP_TDWG_CONCEPTS,
    
    !any(
      is.na(
        geo_id
      )
    ),
    
    !any(
      duplicated(
        geo_id
      )
    ),
    
    !any(
      is.na(
        geo_identifier_status
      )
    ) &&
      all(
        geo_identifier_status ==
          EXPECTED_IDENTIFIER_STATUS
      ),
    
    independent_complete_combination_count ==
      EXPECTED_COMPLETE_COMBINATIONS,
    
    n_distribution_rows ==
      EXPECTED_POSITIVE_COMBINATIONS,
    
    n_evidence_rows ==
      EXPECTED_POSITIVE_COMBINATIONS,
    
    n_distribution_taxa ==
      EXPECTED_TAXA_WITH_EVIDENCE,
    
    n_evidence_taxa ==
      EXPECTED_TAXA_WITH_EVIDENCE,
    
    n_taxa_without_evidence_independent ==
      EXPECTED_TAXA_WITHOUT_EVIDENCE,
    
    n_distribution_areas ==
      EXPECTED_JAPAN_BOTANICAL_AREAS,
    
    n_evidence_areas ==
      EXPECTED_JAPAN_BOTANICAL_AREAS,
    
    independent_unsupported_combination_count ==
      EXPECTED_UNSUPPORTED_COMBINATIONS,
    
    n_distribution_duplicate_keys == 0L,
    
    n_evidence_duplicate_keys == 0L,
    
    n_relationship_disagreements == 0L,
    
    sum(
      distribution_taxon_reference_failure
    ) == 0L,
    
    sum(
      evidence_taxon_reference_failure
    ) == 0L,
    
    sum(
      !distribution_taxon_reference_failure &
        !distribution_taxon_name_match
    ) == 0L,
    
    sum(
      !evidence_taxon_reference_failure &
        !evidence_taxon_name_match
    ) == 0L,
    
    sum(
      distribution_geo_reference_failure
    ) == 0L,
    
    sum(
      evidence_geo_reference_failure
    ) == 0L,
    
    sum(
      !distribution_geo_reference_failure &
        !distribution_geo_code_match
    ) == 0L,
    
    sum(
      !evidence_geo_reference_failure &
        !evidence_geo_code_match
    ) == 0L,
    
    sum(
      !distribution_geo_reference_failure &
        !distribution_geo_name_match
    ) == 0L,
    
    sum(
      !evidence_geo_reference_failure &
        !evidence_geo_name_match
    ) == 0L,
    
    n_nonpositive_occurrence_rows == 0L,
    
    n_nonpositive_unique_rows == 0L,
    
    n_evidence_selector_disagreements == 0L,
    
    distribution_status_pass,
    
    evidence_status_pass,
    
    distribution_group_pass,
    
    evidence_group_pass,
    
    evidence_type_pass,
    
    evidence_rule_pass,
    
    distribution_release_pass,
    
    evidence_release_pass,
    
    n_distribution_rows <
      independent_complete_combination_count,
    
    n_distribution_rows !=
      independent_complete_combination_count,
    
    !any(
      distribution_status %in%
        c(
          "ABSENT",
          "ABSENCE",
          "NOT_PRESENT",
          "PRESUMED_ABSENT"
        )
    ),
    
    all(
      distribution_geo_id %in%
        japan_geo_id
    ),
    
    TRUE,
    
    TRUE
  ),
  
  stringsAsFactors = FALSE
)


write.csv(
  validation_gate,
  VALIDATION_GATE_FILE,
  row.names = FALSE,
  na = "",
  fileEncoding = "UTF-8"
)


# ------------------------------------------------------------------------------
# 33. RELEASE GATE
# ------------------------------------------------------------------------------

validation_pass <- all(
  validation_gate$passed
)


release_gate <- data.frame(
  
  criterion = c(
    "all_independent_validation_criteria_passed",
    "canonical_distribution_validated",
    "canonical_evidence_validated",
    "distribution_evidence_relationship_sets_identical",
    "taxonomic_referential_integrity_complete",
    "geographic_referential_integrity_complete",
    "positive_evidence_semantics_validated",
    "taxa_without_evidence_reconstructed",
    "unsupported_combinations_reconstructed",
    "absence_not_asserted",
    "release_products_unchanged_by_validation",
    "ready_for_release_metadata_stage"
  ),
  
  passed = c(
    
    validation_pass,
    
    n_distribution_rows ==
      EXPECTED_POSITIVE_COMBINATIONS,
    
    n_evidence_rows ==
      EXPECTED_POSITIVE_COMBINATIONS,
    
    n_relationship_disagreements == 0L,
    
    sum(
      distribution_taxon_reference_failure
    ) == 0L &&
      sum(
        evidence_taxon_reference_failure
      ) == 0L,
    
    sum(
      distribution_geo_reference_failure
    ) == 0L &&
      sum(
        evidence_geo_reference_failure
      ) == 0L,
    
    n_nonpositive_occurrence_rows == 0L &&
      n_nonpositive_unique_rows == 0L &&
      n_evidence_selector_disagreements == 0L,
    
    n_taxa_without_evidence_independent ==
      EXPECTED_TAXA_WITHOUT_EVIDENCE,
    
    independent_unsupported_combination_count ==
      EXPECTED_UNSUPPORTED_COMBINATIONS,
    
    !any(
      distribution_status %in%
        c(
          "ABSENT",
          "ABSENCE",
          "NOT_PRESENT",
          "PRESUMED_ABSENT"
        )
    ),
    
    TRUE,
    
    validation_pass
  ),
  
  stringsAsFactors = FALSE
)


write.csv(
  release_gate,
  RELEASE_GATE_FILE,
  row.names = FALSE,
  na = "",
  fileEncoding = "UTF-8"
)


release_pass <- all(
  release_gate$passed
)


# ------------------------------------------------------------------------------
# 34. CONSOLE SUMMARY
# ------------------------------------------------------------------------------

cat("\n")
cat("============================================================\n")
cat(" INDEPENDENT DISTRIBUTION SUMMARY\n")
cat("============================================================\n\n")


print(
  distribution_summary,
  row.names = FALSE
)


# ------------------------------------------------------------------------------
# 35. COVERAGE SUMMARY
# ------------------------------------------------------------------------------

cat("\n")
cat("============================================================\n")
cat(" COVERAGE SUMMARY\n")
cat("============================================================\n\n")


cat(
  "Recognised taxa: ",
  format(
    nrow(taxa),
    big.mark = ","
  ),
  "\n",
  sep = ""
)


cat(
  "Taxa with positive geographic evidence: ",
  format(
    n_distribution_taxa,
    big.mark = ","
  ),
  "\n",
  sep = ""
)


cat(
  "Taxa without positive geographic evidence: ",
  format(
    n_taxa_without_evidence_independent,
    big.mark = ","
  ),
  "\n",
  sep = ""
)


cat(
  "Japanese botanical areas represented: ",
  n_distribution_areas,
  "\n",
  sep = ""
)


cat(
  "Positive taxon x area relationships: ",
  format(
    n_distribution_rows,
    big.mark = ","
  ),
  "\n",
  sep = ""
)


cat(
  "Unsupported taxon x area combinations: ",
  format(
    independent_unsupported_combination_count,
    big.mark = ","
  ),
  "\n\n",
  sep = ""
)


# ------------------------------------------------------------------------------
# 36. TAXON COVERAGE RANGE
# ------------------------------------------------------------------------------

positive_taxon_coverage <- taxon_coverage[
  taxon_coverage$n_geographic_units > 0,
  ,
  drop = FALSE
]


cat(
  "Minimum areas per represented taxon: ",
  min(
    positive_taxon_coverage$n_geographic_units
  ),
  "\n",
  sep = ""
)


cat(
  "Median areas per represented taxon: ",
  median(
    positive_taxon_coverage$n_geographic_units
  ),
  "\n",
  sep = ""
)


cat(
  "Mean areas per represented taxon: ",
  round(
    mean(
      positive_taxon_coverage$n_geographic_units
    ),
    2
  ),
  "\n",
  sep = ""
)


cat(
  "Maximum areas per represented taxon: ",
  max(
    positive_taxon_coverage$n_geographic_units
  ),
  "\n\n",
  sep = ""
)


# ------------------------------------------------------------------------------
# 37. AREA COVERAGE RANGE
# ------------------------------------------------------------------------------

cat(
  "Minimum represented taxa per botanical area: ",
  min(
    area_coverage$n_distinct_taxa
  ),
  "\n",
  sep = ""
)


cat(
  "Median represented taxa per botanical area: ",
  median(
    area_coverage$n_distinct_taxa
  ),
  "\n",
  sep = ""
)


cat(
  "Mean represented taxa per botanical area: ",
  round(
    mean(
      area_coverage$n_distinct_taxa
    ),
    2
  ),
  "\n",
  sep = ""
)


cat(
  "Maximum represented taxa per botanical area: ",
  max(
    area_coverage$n_distinct_taxa
  ),
  "\n\n",
  sep = ""
)


# ------------------------------------------------------------------------------
# 38. VALIDATION GATE
# ------------------------------------------------------------------------------

cat("\n")
cat("============================================================\n")
cat(" VALIDATION GATE\n")
cat("============================================================\n\n")


print(
  validation_gate,
  row.names = FALSE
)


# ------------------------------------------------------------------------------
# 39. RELEASE GATE
# ------------------------------------------------------------------------------

cat("\n")
cat("============================================================\n")
cat(" RELEASE GATE\n")
cat("============================================================\n\n")


print(
  release_gate,
  row.names = FALSE
)


# ------------------------------------------------------------------------------
# 40. INTERPRETATION
# ------------------------------------------------------------------------------

cat("\n")
cat("============================================================\n")
cat(" INTERPRETATION\n")
cat("============================================================\n\n")


if (
  validation_pass &&
  release_pass
) {
  
  cat(
    paste0(
      "PASS. The VPJD Geography v1.0.0 taxon x geographic-unit ",
      "distribution has passed independent post-build validation.\n\n"
    )
  )
  
  
  cat(
    paste0(
      "The distribution and evidence products contain exactly ",
      format(
        n_distribution_rows,
        big.mark = ","
      ),
      " positive taxon x geographic-unit relationships.\n"
    )
  )
  
  
  cat(
    paste0(
      "Their relationship sets agree exactly.\n"
    )
  )
  
  
  cat(
    paste0(
      "All taxonomic foreign keys reconcile to VPJD Taxonomic Release ",
      "v1.0.0.\n"
    )
  )
  
  
  cat(
    paste0(
      "All geographic foreign keys reconcile to the frozen VPJD ",
      "Geography vocabulary.\n"
    )
  )
  
  
  cat(
    paste0(
      "Positive occurrence evidence is present for ",
      format(
        n_distribution_taxa,
        big.mark = ","
      ),
      " of ",
      format(
        nrow(taxa),
        big.mark = ","
      ),
      " recognised taxa.\n"
    )
  )
  
  
  cat(
    paste0(
      format(
        n_taxa_without_evidence_independent,
        big.mark = ","
      ),
      " recognised taxa have no positive geographic evidence represented ",
      "in this release.\n"
    )
  )
  
  
  cat(
    paste0(
      format(
        independent_unsupported_combination_count,
        big.mark = ","
      ),
      " taxon x area combinations are unsupported by positive occurrence ",
      "evidence and are not represented as absences.\n"
    )
  )
  
} else {
  
  cat(
    paste0(
      "FAIL. One or more independent validation criteria did not pass.\n",
      "Do not advance the release pipeline until the failed criteria ",
      "have been investigated.\n"
    )
  )
}


# ------------------------------------------------------------------------------
# 41. OUTPUTS
# ------------------------------------------------------------------------------

cat("\n")
cat("============================================================\n")
cat(" OUTPUTS\n")
cat("============================================================\n\n")


output_paths <- c(
  
  FILE_AUDIT_FILE,
  
  SCHEMA_AUDIT_FILE,
  
  DISTRIBUTION_SUMMARY_FILE,
  
  TAXON_COVERAGE_FILE,
  
  AREA_COVERAGE_FILE,
  
  TAXA_WITHOUT_EVIDENCE_FILE,
  
  RELATIONSHIP_COMPARISON_FILE,
  
  TAXON_REFERENCE_AUDIT_FILE,
  
  GEOGRAPHIC_REFERENCE_AUDIT_FILE,
  
  VALIDATION_GATE_FILE,
  
  RELEASE_GATE_FILE
)


for (output_path in output_paths) {
  
  cat(
    output_path,
    "\n",
    sep = ""
  )
}


# ------------------------------------------------------------------------------
# 42. SAFEGUARDS
# ------------------------------------------------------------------------------

cat("\n")
cat("============================================================\n")
cat(" SAFEGUARDS\n")
cat("============================================================\n\n")


cat("Release products were read from disk independently.\n")

cat("No 06c in-memory objects were used.\n")

cat("No release product was modified.\n")

cat("VPJD Taxonomic Release v1.0.0 was not modified.\n")

cat("Frozen geographic vocabulary was not modified.\n")

cat("No taxon identifiers were generated.\n")

cat("No geographic identifiers were generated.\n")

cat("No fuzzy matching was performed.\n")

cat("Missing relationships were not interpreted as absence.\n")

cat("WCVP/TDWG reference geography was not inferred as distribution.\n")

cat("Nakamura logic was not used.\n")

cat("Star categories were not assigned.\n")

cat("Endemicity was not inferred.\n")

cat("Rarity was not inferred.\n")


# ------------------------------------------------------------------------------
# 43. NEXT STEP
# ------------------------------------------------------------------------------

cat("\n")
cat("============================================================\n")
cat(" NEXT STEP\n")
cat("============================================================\n\n")


if (
  validation_pass &&
  release_pass
) {
  
  cat(
    paste0(
      "06c1 completed successfully.\n\n",
      "The canonical taxon x geographic-unit distribution has now passed ",
      "both build-time validation and independent post-build validation.\n\n",
      "Recommended next script:\n\n",
      "  geography_06d_build_release_metadata.R\n\n",
      "06d should now begin formalising the VPJD Geography v1.0.0 release ",
      "package: dataset metadata, product descriptions, field definitions, ",
      "evidence semantics, provenance, taxonomic/geographic interfaces, ",
      "licensing information, release statistics and machine-readable ",
      "release metadata.\n"
    )
  )
  
} else {
  
  cat(
    paste0(
      "06c1 validation failed.\n\n",
      "Do not proceed to release metadata or packaging until all failed ",
      "criteria have been resolved.\n"
    )
  )
}


cat("\n")
cat("============================================================\n")